{% set name = "modflow-devtools" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a3aaee876eb54b7a84b48477034666c3a1438f23baa84b96367c7ddddc84c663

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - modflow_devtools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MODFLOW-USGS/modflow-devtools
  summary: Python tools for MODFLOW development
  license: CC0-1.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jdhughes-usgs
    - wpbonelli
