{% set name = "modflow-devtools" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d9f454897df99157f72153e57a7561e9fd7067d8393dff319b3d99fa18d30948

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - modflow_devtools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MODFLOW-USGS/modflow-devtools
  summary: Python tools for MODFLOW development
  license: CC0-1.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jdhughes-dev
    - wpbonelli
