{% set name = "modflow-devtools" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e443940002bf84068532f3d0dda81d0e9c474e436944d754299eea64e6c88dd7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - pip
  run:
    - python >=3.8

test:
  imports:
    - modflow_devtools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MODFLOW-USGS/modflow-devtools
  summary: Python tools for MODFLOW development
  license: CC0-1.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jdhughes-usgs
    - wpbonelli
