{% set name = "modflow-devtools" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d99713ff1e1fa00cf7c4b6dc0654492f4fd0ce13318ed8a65e801c4bd47754af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - modflow_devtools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MODFLOW-USGS/modflow-devtools
  summary: Python tools for MODFLOW development
  license: CC0-1.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jdhughes-dev
    - wpbonelli
